'use client';
import {useEffect,useRef,useState} from 'react';
import {api,post,stateNames} from '../lib/api';
import {Notice,JsonDetails} from './UI';
import {Efficiency} from './Research';

const steps=[['transcription','Приём идеи'],['understanding','Разбор задачи'],['research','Исследование'],['planning','Выбор вариантов'],['experiments','Пробные запуски'],['calculation','Измерения'],['assessment','Критическая оценка'],['report','Отчёт']];
export default function AutonomousIdea({idea,mode,refresh,onReport}:{idea:any;mode:string;refresh:()=>void;onReport:()=>void}){
  const [run,setRun]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[answer,setAnswer]=useState('');
  const requestKey=useRef('');const latest=idea.runs[0];
  useEffect(()=>{let live=true;api(`/ideas/${idea.id}/runs/${latest.id}`).then(value=>{if(live)setRun(value);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[idea,latest.id]);
  if(!run||run.id!==latest.id)return error?<Notice kind="error">{error}</Notice>:<p role="status">Загружаем ход работы…</p>;
  const result=(name:string)=>run.steps.find((step:any)=>step.step_id===name&&step.result.status==='completed')?.result.data;
  const understood=result('understanding'),card=understood?.card||idea.content,plan=result('planning'),research=result('research');
  const calculation=run.calculations?.[0]?.content;
  const waiting=['waiting_for_data','waiting_for_user'].includes(run.status);
  const questions=understood&&!understood.can_research?understood.questions:plan?.questions||[];
  async function command(action:string){setBusy(true);setError('');try{await post(`/ideas/${idea.id}/runs/${run.id}/commands`,{action});refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function manage(action:string,priority?:number){setBusy(true);setError('');try{await post(`/ideas/${idea.id}/actions`,{action,priority});refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section><header className="page-heading"><div><h1>{card.title}</h1><p>{stateNames[run.status]||run.status} · версия идеи {idea.current_version}</p></div>{idea.reports.length>0&&<button className="primary" onClick={onReport}>Открыть отчёт</button>}</header>
    {error&&<Notice kind="error">{error}</Notice>}
    {run.stale&&<Notice>Это исследование относится к прежнему описанию идеи.</Notice>}
    {run.job?.last_error&&<Notice kind={waiting?'warning':'error'}>{run.job.last_error}</Notice>}
    <div className="actions">{['ready','running'].includes(run.status)?<><button className="secondary" disabled={busy} onClick={()=>void command('pause')}>Приостановить</button><button className="secondary" disabled={busy} onClick={()=>void command('cancel')}>Остановить</button></>:['paused','error','waiting_for_user'].includes(run.status)?<button className="secondary" disabled={busy} onClick={()=>void command(run.status==='error'?'retry':'resume')}>Продолжить работу</button>:null}</div>
    <ol className="auto-progress" aria-label="Этапы работы">{steps.map(([id,label])=>{const saved=result(id);return <li key={id} className={saved?'done':''}><span>{saved?'✓':'○'}</span>{label}</li>;})}</ol>
    {mode!=='chart'&&<><div className="section-stack"><h2>Как ферма поняла идею</h2>{understood?<><p>{card.problem||card.transcript}</p><dl className="idea-summary">{[['audience','Для кого'],['value','Предлагаемая ценность'],['current_process','Текущий процесс'],['expected_effect','Ожидаемый результат']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{card[key]||'Пока не известно'}{card.knowledge?.[key]==='assumed'&&<small> · предположение</small>}</dd></div>)}</dl>{understood.assumptions.length>0&&<details><summary>Предположения</summary><ul>{understood.assumptions.map((item:string,i:number)=><li key={i}>{item}</li>)}</ul></details>}</>:<p>Агенты разбирают исходное описание. Заполнять карточку вручную не требуется.</p>}</div>
      {research&&<div className="section-stack"><h2>Что выяснили</h2><p>{research.summary}</p><h3>Альтернативы</h3>{research.alternatives.map((item:any,i:number)=><p key={i}><strong>{item.name}</strong> — {item.applicability}</p>)}</div>}
      {plan&&<div className="section-stack"><h2>Подготовленный план проверки</h2><p>{plan.scenario}</p><div className="auto-candidates">{plan.candidates.map((candidate:any)=><article key={candidate.id}><h3>{candidate.name}</h3><p>{candidate.approach}</p></article>)}</div><h3>Что проверяем</h3><ul>{plan.success_criteria.map((criterion:string,i:number)=><li key={i}>{criterion}</li>)}</ul>{plan.execution_limitations.length>0&&<Notice>{plan.execution_limitations.join(' ')}</Notice>}<p><strong>Следующий шаг:</strong> {plan.next_action}</p></div>}
    </>}
    {calculation&&<div className="section-stack"><Efficiency calculation={calculation}/></div>}
    {run.experiments?.length>0&&<details className="section-stack"><summary>Посмотреть входы и результаты пробных запусков</summary><Notice>Это реальные вызовы ИИ на примерах, подготовленных агентом. Они не подтверждают бизнес-эффект.</Notice>{run.experiments.map((experiment:any)=><div key={experiment.id}><h3>{plan?.candidates.find((c:any)=>c.id===experiment.solution_id)?.name||'Вариант'}</h3>{experiment.observations?.map((observation:any)=><details key={observation.id}><summary>Пример {observation.task_id} · повтор {observation.repetition+1}</summary><p>{observation.content.inputs?.provider?.text}</p>{Object.entries(observation.content.output||{}).map(([key,value])=><p key={key}><strong>{plan?.output_fields.find((f:any)=>f.name===key)?.label||key}:</strong> {String(value)}</p>)}</details>)}</div>)}</details>}
    {idea.stage!=='archived'&&<div className="section-stack"><h2>{waiting?'Уточнение для продолжения':'Хотите что-то уточнить?'}</h2>{questions.length>0&&<ul>{questions.map((question:string,i:number)=><li key={i}>{question}</li>)}</ul>}<p>Ответьте своими словами или скорректируйте понимание идеи. Ферма сама подготовит продолжение; предыдущие результаты сохранятся.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');requestKey.current ||= crypto.randomUUID();try{await post(`/ideas/${idea.id}/continue`,{description:answer,idempotency_key:requestKey.current,expected_version:idea.current_version});setAnswer('');requestKey.current='';refresh();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label>Уточнение<textarea rows={3} minLength={3} maxLength={16000} required value={answer} disabled={busy} onChange={e=>{setAnswer(e.target.value);requestKey.current='';}}/></label><button className="primary" disabled={busy||answer.trim().length<3}>Передать агентам</button></form></div>}
    <details className="section-stack"><summary>Управление идеей и исходное описание</summary><p>{result('transcription')?.transcript||idea.content.transcript||'Ожидаем расшифровку'}</p><label className="short-field">Приоритет<select value={idea.priority} disabled={busy} onChange={e=>void manage('priority',Number(e.target.value))}><option value={2}>Высокий</option><option value={1}>Средний</option><option value={0}>Низкий</option></select></label><button className="secondary" disabled={busy} onClick={()=>void manage(idea.stage==='archived'?'activate':'archive')}>{idea.stage==='archived'?'Вернуть из архива':'Архивировать идею'}</button></details>
    <details className="section-stack"><summary>Техническая история</summary><JsonDetails title="Контракты и результаты шагов" value={run.steps}/></details>
  </section>;
}
