'use client';
import {useEffect,useState} from 'react';
import {post,formatDate,api} from '../lib/api';
import {Empty,Notice,JsonDetails} from './UI';
import {Efficiency} from './Research';
import MvpPanel from './MvpPanel';
import ProcessTimer from './ProcessTimer';

export default function Reports({idea,refresh}:{idea:any;refresh:()=>void}){
  const [reportId,setReportId]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [decision,setDecision]=useState('Сначала проверить'),[reason,setReason]=useState(''),[acceptance,setAcceptance]=useState(''),[mvpText,setMvpText]=useState(''),[mvpResult,setMvpResult]=useState<any>(null);
  const [observation,setObservation]=useState({metric:'monthly_volume',target:'',actual:'',unit:'tasks/month',source:''});
  const row=idea.reports.find((r:any)=>r.id===reportId)||idea.reports[0];const mvp=idea.mvp_versions[0];
  useEffect(()=>{if(row?.content?.autonomous){setAcceptance((row.content.plan?.mvp_acceptance||[]).join('\n'));setReason('Согласен с выводами и следующим шагом отчёта.');setDecision(row.content.assessment?.recommendation||'Сначала проверить');}},[row?.id]);
  async function action(fn:()=>Promise<any>){setBusy(true);setError('');setMessage('');try{await fn();refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section><header className="page-heading"><div><h1>Отчёт и решение</h1><p>{idea.title}</p></div>{row&&<select aria-label="Версия отчёта" value={row.id} onChange={e=>setReportId(e.target.value)}>{idea.reports.map((r:any)=><option key={r.id} value={r.id}>Отчёт v{r.version} · {formatDate(r.created_at)}</option>)}</select>}</header>
    {error&&<Notice kind="error">{error}</Notice>}{message&&<Notice>{message}</Notice>}
    {!row?<Empty title="Отчёт ещё не готов" text="Завершите исследование, реальные прогоны и критическую оценку. Отчёт будет собран из проверенных результатов."/>:<>
      {row.stale&&<Notice kind="error">Этот отчёт относится к предыдущей версии идеи и помечен stale.</Notice>}
      <ReportBody report={row.content}/>
      <div className="section-stack"><div className="inline-heading"><h2>Решение пользователя</h2><button className="secondary" disabled={busy} onClick={()=>void action(async()=>{const r=await post(`/ideas/${idea.id}/reports/${row.id}/publish`);setMessage('Публичная ссылка только для чтения: '+location.origin+r.url);})}>Создать ссылку только для чтения</button></div>{row.public_token&&<a href={'/public/'+row.public_token} target="_blank" rel="noreferrer">Открыть публичный отчёт</a>}
        <label>Ваше решение<select value={decision} onChange={e=>setDecision(e.target.value)}>{['Развивать','Сначала проверить','Отложить','Отклонить','Недостаточно данных'].map(s=><option key={s}>{s}</option>)}</select></label>
        <label>Основание решения<textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>
        {decision==='Развивать'&&<label>Критерии приёмки MVP · по одному на строку<textarea rows={4} placeholder="Что должно пройти проверку до признания MVP готовым?" value={acceptance} onChange={e=>setAcceptance(e.target.value)}/></label>}
        <button className="primary" disabled={busy||!reason.trim()||row.stale} onClick={()=>void action(async()=>{await post(`/ideas/${idea.id}/reports/${row.id}/decision`,{decision,reason,acceptance:acceptance.split('\n').filter(Boolean)});setMessage('Решение сохранено.');})}>Сохранить решение</button>
      </div>
    </>}
    <MvpPanel idea={idea} refresh={refresh}/><details className="section-stack"><summary>Дополнительные измерения и наблюдения</summary><ProcessTimer idea={idea} refresh={refresh}/>
    <div className="section-stack"><h2>Наблюдения и обновление метрик</h2><p>Технические измерения приходят из прогонов. Добавьте бизнес-наблюдение вручную или импортируйте JSON.</p><div className="form-grid">{Object.entries(observation).map(([key,value],i)=><label key={key}>{['Метрика','Целевое значение','Фактическое значение','Единица','Источник'][i]}<input type={key==='target'||key==='actual'?'number':'text'} value={value} onChange={e=>setObservation(o=>({...o,[key]:e.target.value}))}/></label>)}</div><div className="actions"><button className="secondary" disabled={busy||!observation.source||!observation.actual||!observation.target} onClick={()=>void action(async()=>{const r=await post(`/ideas/${idea.id}/observations`,{...observation,target:Number(observation.target),actual:Number(observation.actual),...(['monthly_volume','quality','manual_review_rate'].includes(observation.metric)?{[observation.metric]:Number(observation.actual)}:{})});setMessage(r.message||'Созданы новая версия расчёта и отчёт.');})}>Сохранить и пересчитать</button><label className="file-button">Импорт JSON<input type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)void action(async()=>{await post(`/ideas/${idea.id}/observations`,JSON.parse(await f.text()));setMessage('Наблюдение импортировано.');});}}/></label></div>
      {idea.observations.length?idea.observations.map((o:any,index:number)=>{const previous=idea.observations.slice(index+1).find((p:any)=>p.content.metric===o.content.metric);return <div className="observation" key={o.id}><strong>{o.content.metric}: {o.content.actual} {o.content.unit}</strong><span>Цель: {o.content.target} · {previous?`Изменение: ${o.content.actual-previous.content.actual}`:'Первое наблюдение'}</span><small>{o.content.source} · {formatDate(o.created_at)}</small></div>;}):<p className="muted">Нет данных</p>}
    </div></details>
  </section>;
}
export function ReportBody({report,publicView=false}:{report:any;publicView?:boolean}){
  const r=report.research,a=report.assessment;
  return <div className="report-body"><section className="recommendation"><span className="caption">Резюме и решение</span><h2>{a?.recommendation||'Недостаточно данных'}</h2><p>{report.summary}</p>{a&&<p>Многокритериальный балл: <strong>{a.weighted_score?.toFixed(2)} / 5</strong>. Стоп-факторы проверяются раньше балла.</p>}</section>
    {r&&!publicView&&<><details open><summary>Рынок и альтернативы</summary>{r.alternatives.length?r.alternatives.map((item:any,i:number)=><article className="section-stack" key={i}><h3>{item.name||`Альтернатива ${i+1}`}</h3><p>{item.applicability}</p>{item.limitations?.length>0&&<ul>{item.limitations.map((value:string,j:number)=><li key={j}>{value}</li>)}</ul>}</article>):<p>Достоверные альтернативы не найдены.</p>}
      {r.trends&&<details><summary>Тренды и прогноз</summary><p>Горизонт: {r.trends.horizon}</p><ul>{r.trends.drivers?.map((value:string,i:number)=><li key={i}>{value}</li>)}</ul>{[['adverse','Неблагоприятный'],['base','Базовый'],['favorable','Благоприятный']].map(([key,label])=>r.trends[key]&&<article key={key}><h3>{label} сценарий · прогноз</h3><p>{r.trends[key].description}</p><ul>{r.trends[key].assumptions.map((value:string,i:number)=><li key={i}>{value}</li>)}</ul></article>)}</details>}</details>
      <details><summary>Аудитории и гипотезы</summary><Notice>Синтетическая проверка гипотез. Это не интервью и не подтверждение спроса.</Notice>{r.personas?.map((persona:any,i:number)=><article className="section-stack" key={i}><h3>{persona.role}</h3><p>{persona.job}</p><p><strong>Проблема:</strong> {persona.pain}</p><p><strong>Что используют сейчас:</strong> {persona.alternative}</p><ul>{persona.objections?.map((value:string,j:number)=><li key={j}>{value}</li>)}</ul></article>)}<h3>Что проверить на практике</h3>{r.hypotheses?.map((hypothesis:any,i:number)=><article className="section-stack" key={i}><h3>{hypothesis.claim}</h3><p>{hypothesis.experiment}</p><p><strong>Метрика:</strong> {hypothesis.metric} · <strong>Порог:</strong> {hypothesis.success_threshold}</p><p><strong>Что опровергнет гипотезу:</strong> {hypothesis.falsification}</p></article>)}</details></>}
    {report.plan&&!publicView&&<details open><summary>План, подготовленный фермой</summary><p>{report.plan.scenario}</p>{report.plan.candidates.map((candidate:any)=><article key={candidate.id}><h3>{candidate.name}</h3><p>{candidate.approach}</p></article>)}<h3>Критерии проверки</h3><ul>{report.plan.success_criteria.map((value:string,i:number)=><li key={i}>{value}</li>)}</ul><p><strong>Следующий шаг:</strong> {report.plan.next_action}</p>{report.plan.questions.length>0&&<><h3>Какие сведения помогут продолжить</h3><ul>{report.plan.questions.map((value:string,i:number)=><li key={i}>{value}</li>)}</ul><p>Ответ можно передать агентам в карточке идеи.</p></>}</details>}
    {report.calculation&&<details open><summary>Эффективность, прогноз и метрики</summary><Efficiency calculation={report.calculation}/></details>}
    {a&&<details open><summary>Критическая оценка и риски</summary><ol className="checks">{a.checks.map((c:any)=><li key={c.name}><strong>{c.passed?'Пройдено':'Не пройдено'} · {c.name}</strong><p>{c.reason}</p></li>)}</ol><h3>Следующий эксперимент</h3><p>{a.next_experiment}</p><JsonDetails title="Доказательность, оценки и ограничения" value={{factors:a.evidence_factors,scores:a.scores,limitations:a.score_limitations,gaps:a.gaps}}/></details>}
    {r&&!publicView&&<details><summary>Источники</summary>{r.sources.map((s:any)=><div className="source" key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title||s.url}</a><p>{s.organization} · {s.availability==='available'?'Доступен':'Недоступен'} · {s.publication_date||'Дата публикации неизвестна'}</p><small>Проверено: {s.accessed_at}</small></div>)}</details>}
    <details><summary>Версии и история</summary><JsonDetails title="Цепочка прослеживаемости" value={report.versions}/>{report.changed_inputs&&<JsonDetails title="Какие входы изменили расчёт" value={report.changed_inputs}/>}</details>
  </div>;
}
