'use client';
import {useEffect,useState} from 'react';
import {api,post,stateNames,formatDate} from '../lib/api';
import {Empty,Notice,JsonDetails,NumberValue,Icon} from './UI';

export default function Research({idea,mode,refresh}:{idea:any;mode:string;refresh:()=>void}){
  const [run,setRun]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[datasetId,setDatasetId]=useState(idea.datasets[0]?.version_id||'');
  const [prompts,setPrompts]=useState(['Определи главную цель обращения и выбери одну разрешённую категорию.','Оцени неоднозначность и риски неверной маршрутизации. При сомнении запроси ручную проверку.']);
  const [sources,setSources]=useState(''),[blockers,setBlockers]=useState(''),[thresholds,setThresholds]=useState({minimum_effect_seconds:1,minimum_quality:.9,maximum_manual_review:.2,maximum_error:.1});
  const latest=idea.runs[0];
  useEffect(()=>{if(latest)api(`/ideas/${idea.id}/runs/${latest.id}`).then(setRun).catch(e=>setError(e.message));},[idea,latest]);
  async function upload(file:File){setBusy(true);setError('');try{const data=JSON.parse(await file.text());const result=await post(`/ideas/${idea.id}/datasets`,data);setDatasetId(result.version_id);refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function start(){setBusy(true);setError('');try{await post(`/ideas/${idea.id}/runs`,{idempotency_key:crypto.randomUUID(),dataset_version_id:datasetId,variant_prompts:prompts,source_urls:sources.split('\n').map(s=>s.trim()).filter(Boolean),hard_blockers:blockers.split('\n').filter(Boolean),thresholds});refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const calculation=run?.calculations?.[0]?.content;
  return <section><header className="page-heading"><div><h1>{mode==='chart'?'Прогоны и эффективность':'Ход проверки'}</h1><p>{idea.title}</p></div></header>{error&&<Notice kind="error">{error}</Notice>}
    {mode==='activity'&&<>
      <JsonDetails title="Результаты и контракты агентных ролей" value={idea.agent_results||[]}/>
      {run&&<div className="run-progress"><div className="inline-heading"><h2>{stateNames[run.status]||run.status}</h2><span>{run.call_count} ИИ-вызовов · {formatDate(run.created_at)}</span></div>{run.stale&&<Notice>Входы изменились. Результаты этого запуска устарели.</Notice>}{run.job?.last_error&&<Notice kind="error">{run.job.last_error}</Notice>}<div className="actions">{['pause','resume','cancel','retry'].map((action,i)=><button className="secondary" key={action} onClick={async()=>{try{await post(`/ideas/${idea.id}/runs/${run.id}/commands`,{action});refresh();}catch(e){setError((e as Error).message);}}}>{['Пауза','Продолжить','Отменить','Повторить сбойный шаг'][i]}</button>)}</div><ol className="step-list">{['research','experiments','calculation','assessment','report'].map((id,i)=>{const step=run.steps.find((s:any)=>s.step_id===id);return <li key={id}><span className={'step-number '+(step?'done':'')}>{step?'✓':i+1}</span><div><strong>{['Исследование','Реальные прогоны','Расчёт эффективности','Критическая оценка','Отчёт'][i]}</strong><p>{step?`${step.result.conclusion} · ${step.result.duration_ms} ms`:'Ожидает выполнения'}</p>{step&&<JsonDetails title="Контракт и результат" value={step.result}/>}</div></li>;})}</ol></div>}
      <div className="section-stack"><h2>Подготовить исследование</h2><p>Сравните исходный процесс и два варианта на одном наборе задач. Пороги фиксируются до запуска.</p>
        <div className="form-grid"><label>Тестовый набор<select value={datasetId} onChange={e=>setDatasetId(e.target.value)}><option value="">Загрузите JSON-набор</option>{idea.datasets.map((d:any)=><option value={d.version_id} key={d.version_id}>{d.name} · v{d.version} · {d.content.rows.length} задач</option>)}</select></label><label>Загрузить набор<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/></label></div>
        <JsonDetails title="Формат JSON-набора: замените пример собственными наблюдениями" value={{name:'Название набора',source:'Источник реальных измерений',period:'Период наблюдений',provenance:'measured',labels:['категория_1','категория_2'],rows:[{task_id:'уникальный ID',input:'Исходное обращение',expected_label:'категория_1',baseline_seconds:null,baseline_correct:null,manual_review_seconds:0,error_correction_seconds:0}]}}/>
        <p className="caption">Нужно минимум 2 задачи. Для содержательной статистики — от 5. При двух вариантах и трёх повторах лимит 40 ИИ-вызовов позволяет до 6 задач за запуск. Пропуски baseline сохраняются как null.</p>
        <div className="form-grid">{prompts.map((prompt,i)=><label key={i}>Вариант {String.fromCharCode(65+i)}<textarea rows={4} maxLength={4000} value={prompt} onChange={e=>setPrompts(p=>p.map((s,j)=>i===j?e.target.value:s))}/></label>)}</div>
        <div className="form-grid">{Object.entries(thresholds).map(([key,value],i)=><label key={key}>{['Минимальный эффект · sec/task','Минимальное качество · доля','Максимальная ручная проверка · доля','Допустимая ошибка · доля'][i]}<input type="number" min={0} max={i?1:undefined} step={i ? 0.01 : 0.1} value={value} onChange={e=>setThresholds(t=>({...t,[key]:Number(e.target.value)}))}/></label>)}</div>
        <label>Источники · публичные HTTPS-ссылки по одной на строку<textarea rows={5} placeholder="Необязательно: без ссылок Worker выполнит веб-поиск Groq" value={sources} onChange={e=>setSources(e.target.value)}/></label><p className="caption">Для полного исследования нужны пять релевантных источников. Worker читает указанные страницы и отмечает недоступные. Без ссылок используется Groq Compound Mini с разрешённым только web_search.</p>
        <label>Стоп-факторы<textarea rows={3} placeholder="Какие обстоятельства исключают развитие идеи?" value={blockers} onChange={e=>setBlockers(e.target.value)}/></label>
        <button className="primary" disabled={busy||!datasetId} onClick={()=>void start()}><Icon name="activity"/>{busy?'Постановка в очередь…':'Запустить проверку'}</button>
      </div>
    </>}
    {mode==='chart'&&(calculation?<><Efficiency calculation={calculation}/>{run.experiments.map((e:any)=><JsonDetails key={e.id} title={`Прогон ${e.id.slice(0,8)} · ${e.status}`} value={e}/>)}</>:<Empty title="Расчётов пока нет" text="Подготовьте baseline, тестовый набор и запустите проверку. Здесь появятся реальные измерения и интервалы."/>)}
  </section>;
}
export function Efficiency({calculation}:{calculation:any}){
  if(calculation.mode==='autonomous_trials')return <section><h2>Результаты технической проверки</h2><Notice>Время измерено на реальных вызовах. Примеры подготовлены агентом; качество для бизнеса и экономия времени пока не подтверждены.</Notice><div className="table-scroll"><table><thead><tr><th>Вариант</th><th>Среднее время, сек.</th><th>Примеров</th><th>Запусков</th><th>Соответствие схеме</th></tr></thead><tbody>{calculation.variants.map((variant:any)=><tr key={variant.solution_id}><td>{variant.name}</td><td><NumberValue value={variant.measured_chain_mean_seconds}/></td><td>{variant.sample_size}</td><td>{variant.observation_count}</td><td><NumberValue value={variant.schema_valid_rate==null?null:variant.schema_valid_rate*100}/>%</td></tr>)}</tbody></table></div><p className="caption">Среднее время = сумма длительностей / число запусков. Повторы не увеличивают число независимых примеров. Проверка схемы не оценивает смысловую правильность ответа.</p><p>Для расчёта эффекта нужны реальные примеры исходного процесса, замеры времени и проверка полезности ответов. Эти данные не подменяются предположениями.</p></section>;
  const demo=calculation.variants.some((v:any)=>v.provenance==='demo');
  return <div className="section-stack"><div className="inline-heading"><h2>Сравнение вариантов</h2><span>Расчёт v{calculation.version} · {calculation.period}</span></div>{demo&&<Notice kind="warning">Демонстрационные данные. Baseline и обращения синтетические; показанные разницы и прогнозы не доказывают бизнес-эффект.</Notice>}<Notice>Измеренное время цепочки и качество на тестовом наборе показаны отдельно от модельных сценариев внедрения.</Notice><div className="table-scroll"><table><thead><tr><th>Вариант</th><th>Baseline, сек</th><th>Вариант, сек</th><th>Эффект, sec/task</th><th>Качество</th><th>n</th></tr></thead><tbody>{calculation.variants.map((v:any,i:number)=><tr key={v.solution_id}><th>Вариант {String.fromCharCode(65+i)}</th><td><NumberValue value={v.baseline_mean_seconds}/></td><td><NumberValue value={v.variant_mean_seconds}/></td><td><NumberValue value={v.statistical?.point_estimate}/></td><td><NumberValue value={v.quality==null?null:v.quality*100}/>%</td><td>{v.sample_size}</td></tr>)}</tbody></table></div>
    {calculation.variants.map((v:any,i:number)=><div className="calculation-block" key={v.solution_id}><h3>Вариант {String.fromCharCode(65+i)} · время цепочки и сравнение с baseline</h3><p>Измеренное время: <strong><NumberValue value={v.measured_chain_mean_seconds}/> sec/task</strong>. Разница с baseline{v.provenance==='demo'?' (демо)':''}: <strong><NumberValue value={v.measured_chain_effect?.point_estimate}/> sec/task</strong>.</p><h3>Полное время с модельной ручной доработкой · неопределённость</h3>{v.statistical?<p>{v.statistical.confidence_level*100}% интервал: <strong><NumberValue value={v.statistical.lower_bound}/> — <NumberValue value={v.statistical.upper_bound}/> sec/task</strong> · n={v.statistical.sample_size}</p>:<Notice>Недостаточно сопоставимых наблюдений для интервала.</Notice>}<p className="caption">Источник: {calculation.dataset_source}. Метод: paired bootstrap. Положительная разница означает экономию времени. Пропуски baseline: {v.missing_baseline} ({Math.round(v.missing_fraction*100)}%).</p>
      <h3>Потенциальный эффект · прогноз, hours/month</h3><div className="scenario-grid">{Object.entries(v.scenarios).map(([name,s]:[string,any])=><div className="scenario" key={name}><span>{{adverse:'Неблагоприятный',base:'Базовый',favorable:'Благоприятный'}[name]}</span><strong><NumberValue value={s.monthly_hours}/></strong><small>часов в месяц · модель внедрения</small></div>)}</div><p className="caption">Период: месяц. Формула: объём × покрытие × (baseline − полное время внедрения) / 3600. Источники параметров — dataset и явные допущения.</p>
      <JsonDetails title="Метод, исходные параметры, чувствительность и ограничения" value={v}/></div>)}
  </div>;
}



