import {z} from 'zod';
export const field=z.object({name:z.string().regex(/^[a-z][a-z0-9_]{0,39}$/),label:z.string().min(1).max(120),type:z.enum(['string','number','boolean'])}).strict();
export const card=z.object({title:z.string().min(1).max(200),transcript:z.string().max(20000),problem:z.string().max(4000),audience:z.string().max(2000),value:z.string().max(2000),currentProcess:z.string().max(4000),assumptions:z.array(z.string()).max(15),constraints:z.array(z.string()).max(15)}).strict();
export const analysis=z.object({summary:z.string().max(5000),findings:z.array(z.string()).max(15),assumptions:z.array(z.string()).max(15),gaps:z.array(z.string()).max(15)}).strict();
export const audience=z.object({personas:z.array(z.object({role:z.string(),job:z.string(),pain:z.string(),alternative:z.string(),objections:z.array(z.string())}).strict()).max(6),summary:z.string(),assumptions:z.array(z.string())}).strict();
export const research=z.object({summary:z.string(),alternatives:z.array(z.object({name:z.string(),applicability:z.string(),limitations:z.array(z.string()),sourceUrl:z.string()}).strict()).max(10),claims:z.array(z.object({claim:z.string(),sourceId:z.string(),quote:z.string(),provenance:z.enum(['EXTERNAL_FACT','ASSUMED'])}).strict()).max(20),gaps:z.array(z.string()),assumptions:z.array(z.string())}).strict();
export const hypotheses=z.object({items:z.array(z.object({claim:z.string(),audience:z.string(),experiment:z.string(),metric:z.string(),threshold:z.string(),falsification:z.string()}).strict()).min(1).max(8),nextExperiment:z.string()}).strict();
export const webAction=z.discriminatedUnion('action',[
 z.object({action:z.literal('web_search'),query:z.string().min(3).max(500),maxResults:z.number().int().min(1).max(8),freshnessDays:z.number().int().positive().nullable(),domains:z.array(z.string().max(200)).max(5)}).strict(),
 z.object({action:z.literal('read_page'),url:z.string().url().max(2000)}).strict(),
 z.object({action:z.literal('finish'),reason:z.string().max(1000)}).strict()
]);
export const variantPlan=z.object({scenario:z.string().max(2000),executable:z.boolean(),limitations:z.array(z.string()).max(12),fields:z.array(field).min(1).max(8),variants:z.array(z.object({name:z.string().max(150),approach:z.string().max(1200),prompt:z.string().min(1).max(4000),useRules:z.boolean()}).strict()).length(2),acceptance:z.array(z.string()).min(1).max(10)}).strict();
export const datasetPlan=z.object({name:z.string(),source:z.string(),provenance:z.enum(['EXTERNAL_FACT','SIMULATED']),sourceId:z.string().nullable(),baselineDescription:z.string(),monthlyVolume:z.number().nonnegative().nullable(),monthlyVolumeProvenance:z.enum(['ASSUMED','EXTERNAL_FACT']),cases:z.array(z.object({taskId:z.string().max(60),input:z.string().min(1).max(6000),expected:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])).nullable(),baselineSeconds:z.number().nonnegative().nullable(),baselineProvenance:z.enum(['EXTERNAL_FACT','ASSUMED','SIMULATED']),sourceQuote:z.string().nullable()}).strict()).min(2).max(10),warnings:z.array(z.string())}).strict();
export const critique=z.object({summary:z.string(),recommendation:z.enum(['Развивать','Сначала проверить','Отложить','Отклонить','Недостаточно данных']),reasons:z.array(z.string()),counterarguments:z.array(z.string()),nextExperiment:z.string(),hardBlockers:z.array(z.string())}).strict();
export const mvpSpec=z.object({title:z.string().max(200),description:z.string().max(2000),inputFields:z.array(field).min(1).max(8),outputFields:z.array(field).min(1).max(8),prompt:z.string().min(1).max(4000),useRules:z.boolean(),acceptance:z.array(z.string()).min(1).max(10)}).strict();
export type MvpSpec=z.infer<typeof mvpSpec>;
export function fieldsSchema(fields:z.infer<typeof field>[]){return {type:'object',properties:Object.fromEntries(fields.map(f=>[f.name,{type:f.type}])),required:fields.map(f=>f.name),additionalProperties:false};}
export function validateFields(value:unknown,fields:z.infer<typeof field>[]){return z.object(Object.fromEntries(fields.map(f=>[f.name,f.type==='number'?z.number().finite():f.type==='boolean'?z.boolean():z.string().max(16000)]))).strict().parse(value);}
